version: "3.3"

services:
  computer: 
    image: ubuntu:20.04
    container_name: machine
    command: tail -F anything
  
  database:
    image: postgres:14.1
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./dbdata:/var/lib/postgresql/data

